### PR TITLE
Offline rendering fix

### LINKED ISSUE #115: Offline-rendering doesn't work with manually created Tone instrument
Using offline rendering in browser mode:

This will work ✔:
```javascript
const session = new scribble.Session();
session.createChannel({
  instrument: "PolySynth",
  clips: [{ pattern: '[xx]', notes: 'C3 Cm-3' }],
  offlineRendering: true,
});
```

This won't work ❌:
```javascript
const session = new scribble.Session();
synth = new Tone.PolySynth()
session.createChannel({
  instrument: synth,
  clips: [{ pattern: '[xx]', notes: 'C3 Cm-3' }],
  offlineRendering: true,
});
```
The `Tone.Player` returned by the offline rendering contains a buffer filled with zeroes (silence).

### LINKED ISSUE #116: Offline-rendering doesn't work with pattern starting with silence
Using offline rendering in browser mode:

This will work ✔:
```javascript
const session = new scribble.Session();
session.createChannel({
  instrument: "PolySynth",
  clips: [{ pattern: 'xxxx', notes: 'C3 Cm-3' }],
  offlineRendering: true,
});
```

This won't work ❌:
```javascript
const session = new scribble.Session();
session.createChannel({
  instrument: "PolySynth",
  clips: [{ pattern: '--xx', notes: 'C3 Cm-3' }],
  offlineRendering: true,
});
```
The `Tone.Player` returned by the offline rendering contains a buffer filled with zeroes (silence).

### LINKED ISSUE #119: Effects are not connected to destination node
Using this example:
```javascript
const session = new scribble.Session();

const effect = new Tone.AutoWah({Q: 6})
session.createChannel({
  instrument: "Synth",
  clips: [
    { pattern: 'x____x____', notes: 'C3 C3', effects: effect },
    { pattern: 'x____x____', notes: 'C3 C3', effects: "AutoFilter" },
    { pattern: 'x____x____', notes: 'C3 C3' },
  ],
});
```

There are no differences between the clips played.

It's maybe because, in `browserClip` the effects are not connected using to the destination node using `.toDestination()` or `.toMaster()`.

As a workaround, you can connect yourself your manually created effect:
```javascript
const effect = new Tone.AutoWah({Q: 6}).toDestination()
```

But it won't work for effects created inside `browserClip`(e.g: when you pass the param `{ effects: "AutoFilter }`).

### LINKED ISSUE #121: Offline-rendering pattern duration is wrong when there are silences in the pattern
Using this example:
```javascript
const session = new scribble.Session();
session.createChannel({
  instrument: "PolySynth",
  clips: [{ pattern: 'x-x', notes: 'C3 Cm-3' }],
  offlineRendering: true,
});
```
The offline-rendered clip will be 2 notes long, whereas it should be 3 notes long.

The pattern duration is (today) computed as the sum of the notes' lengths, but it is wrong when there are silences in the pattern 😅

### PR DESCRIPTION
**Pull request by qchenevier**
It fixes #115 only for Instrument which are not based on a buffer:
- ✔️ works for `Tone.Synth` or `Tone.Polysynth`
- ❌ doesn't work for `Tone.Player` or `Tone.Sampler`

In order to reset the context for instruments, I have to recreate them using the offline context. With buffer-based instruments, there is an asynchronous process which is filling their buffer after the creation. We need to implement the offline rendering in an asynchronous way for those instruments. Maybe by using their `onload` callback, which is called once their buffer is ready.

I've put a warning & deactivated the offline rendering feature when it is obvious it won't work (e.g: when `samples` are provided as params to `scribble.clip`).

---

Edit: with the last commits, it also fixes: 
- fix #119 
- fix #121 
- fix #116

### CODE REVIEW

File: src/browserClip.ts [hunk 1]
```diff
@@ -215,10 +217,12 @@ const generateSequence = (params: ClipParams) => {
     if (params.volume) {
       params.sampler.volume.value = params.volume;
     }
-    params.sampler.chain(
-      ...effects,
-      Tone.Master ? Tone.Master : Tone.Destination
-    );
+    params.sampler.chain(...effects);
+    if (isToneV13()) {
```
Comment (walmik) [inline src/browserClip.ts:221]: Apologies for bringing this up a bit later than it s already merged but are earlier versions of Tone capable of whatever s in the else?

Comment (qchenevier) [reply src/browserClip.ts:221]: I don't understand this sentence 😅. Can you be more specific ? 😬

Tone version 13 is able to do dynamic rendering (all the scribbletune features except offline rendering), but I guess you know that.

Note: the lines above are only to harmonize the way we handle tone versions in the code. So that when tone 14 is published officially, it will be easier to clean the code, finding all the `if else` statements using `isToneV13()` as condition.

**Comment by qchenevier** [comment]
I've marked this PR as draft as I just realized it might not be working when you add effects. I need to test & maybe fix that.

**Comment by qchenevier** [comment]
This new commit fixes totally #119 and partially #120 (effects are scoped to their clip in offline rendering mode only).

**Comment by qchenevier** [comment]
Found that `totalPatternDuration`computation was wrong when there was silences in the pattern (see #121 ). I added a fix for that & some tests.

**Comment by walmik** [comment]
Apologies for the delay in reviewing this @qchenevier (just been bit busy at work). Is the current state of these changes good to go? (I noticed your comment bout marking this PR as draft - lemme know if that s not the case anymore)

**Comment by qchenevier** [comment]
No worries 😊

Yeah, I think it's ready to merge now.

**Comment by walmik** [comment]
Thank you @qchenevier !

**Comment by walmik** [comment]
@qchenevier can you please create a patch bump PR as well. Unless you wanna combine it with another PR.. that s fine too.

**Comment by qchenevier** [comment]
@walmik Done (see #122 ).
